services:
  bot:
    image: ghcr.io/HgAnh7/BotTele:latest  # thay yourusername/your-bot
    container_name: telegram_bot
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
